[[entry]]
title = "纸牌城堡"
date = 2024-09-09
image_url = "https://2f0f3db.webp.li/2024/09/89956875_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/89956875"
note = "庆祝画廊页面的重构完成！这种感觉确实很像是搭纸牌城堡，莫名有一种契合（笑）"
keywords = ["城堡", "公主", "优雅"]
blurhash = "UxKwCFIURPs:~qaKRjV@%gayV@WBkWs:jFae"

[[entry]]
title = "追寻"
date = 2024-09-10
image_url = "https://2f0f3db.webp.li/2024/09/122295149_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/122295149"
note = "今天是生日，也是准备面试的第二天，忙的连轴转，也算是一起在追寻！总是在寻找一些美好的东西"
keywords = ["银发"]
blurhash = "UADJJ5^-009F=SRh4?IV00E1^+bX0@oh~9xt"

[[entry]]
title = "流星"
date = 2024-09-11
image_url = "https://2f0f3db.webp.li/2024/09/122228116_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/122228116"
note = "流星的意思是出货吗（笑），请假一天，好好准备吧！"
keywords = ["流星", "许愿"]
blurhash = "U9C~Y~x|}$Ae009X0e$,[%^Ekr%N%OAL-XEM"

[[entry]]
title = "雨中音"
date = 2024-09-12
image_url = "https://2f0f3db.webp.li/2024/09/122170357_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/122170357"
note = """
今天有一个华为的宣讲会，到场后深刻感觉了宣讲学长的热情……真的是站着不动都会有人来找你（笑）。华为在我看来还是很硬核的，也许前端并不会招收很多，不过终端部门的学长讲了很多有关前端与华为生态的东西，我似乎也可以尝试一下 arkTs，做一个客户端应用试试看。
除了华为的宣讲会，今天也是我 512 stars 的日子，在 Reddit 上有个人推荐了我的插件，一晚上就多了二三十个 stars，真的感觉很棒，一年多前无心的插柳，现在也算是开花结果，期待 1024 stars 的到来。
不过说实话 neovim 的插件开发有点痛苦，这份痛苦是 Lua 这门语言带来的，非常诡异的语法和简陋的标准库，再加上 neovim 接口设计的也比较混乱，导致我很想放弃 neovim 的插件开发。刚好今天群里看到有群友写了一个 rsvim 项目，rust 作为内核，并且使用 typescript 进行插件开发。这个项目还处于一个相当早期的阶段，不过如果可能的话，我也希望能够尽一份力"""
keywords = ["雨", "紫色", "忧郁"]
blurhash = "U9G[W,Djk;?b00_M00M|0K00xsM|?cRk?H-."

[[entry]]
title = "早！"
date = 2024-09-13
image_url = "https://2f0f3db.webp.li/2024/09/93941224_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/93941224"
note = """
这张图片是凌晨的时候刷 pixiv 看见的，可以说不小心暴露了 XP（乐），这样的早上一定很美好吧！
今天主要是修改 bug，测试给出的 bug 都是陈年老货，七个月之前没有测出来，现在交到了我的手里，谁知道改一下会不会爆出问题呢？
现在看来前端的平均水平还真是令人悲哀，居然都是 copy 来 copy 去，有问题也不知道，不深究代码运行的机制，只是追求代码能跑，没有及时的重构，这样下去，肯定会变得很难维护。还有破窗效应也是体现的淋漓尽致，一个人在代码里面写了无厘头的写法，后面看到的人就会不自觉的给打补丁（往上面堆），要么说领头羊呢"""
keywords = ["早晨", "绝对领域"]
blurhash = "ULI|]]00t,-A~WD%%MRP4.xuxaM{bbNGWVRk"

[[entry]]
title = "自言自语"
date = 2024-09-14
image_url = "https://2f0f3db.webp.li/2024/09/119507114_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/119507114"
note = """
这张图片让我想起了候鸟这个 galgame，就在黄河边的湿地旁，二人半开玩笑而又略带认真的讨论着未来……不知怎的，感同身受啊！
今天还收到了百度的预录取通知，不过这个没有准信，还得去实习才能决定，我可能还要问一下那边的业务主要是什么再做决定，现在的 vue2 已经很折磨了，学习不到新的东西，在舒适区怎么能成长呢？要想完成自己的全栈梦想（一个完整的 APP），还有很长的路要走啊！"""
keywords = ["星空", "思考", "月光"]
blurhash = "UCA]t3xaR%t80eNcoMWA9WogaxWB}sn%W=of"

[[entry]]
title = "四季的窗"
date = 2024-09-15
image_url = "https://2f0f3db.webp.li/2024/09/116362193_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/116362193"
note = """
这是九月十八日补上的日记，重新下载回来了王者荣耀，一个人假期里实在是太闷了，还是和同学打打游戏比较好……不过因为是补充的日记，你也知道后续发生了什么（悲）。
顺带一提，计算了伽罗太华皮肤要想抽到一共需要多少抽，深感概率论的实用性"""
keywords = ["四季", "窗户"]
blurhash = "UQHe%#}Y4TF{BEyF%1Mv0KOa%MrV-ORNM}xv"

[[entry]]
title = "你记录光，我记录你"
date = 2024-09-16
image_url = "https://2f0f3db.webp.li/2024/09/102210467_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/102210467"
note = "想让男女保持同样的理性和思考步调，也许是一种奢望。今天 98 上的帖子实在是令人震撼。"
keywords = ["光影"]
blurhash = "ULC?P]?a-:~V~Vx[xu-:9aNHWXRk9ajGoLRj"

[[entry]]
title = "水畔的风"
date = 2024-09-17
image_url = "https://2f0f3db.webp.li/2024/09/81060731_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/81060731"
note = "最后一天咯，明天的面试就相当于是裸考了！"
keywords = ["风", "湿地", "公主", "城堡"]
blurhash = "UuMG*Jt8WTxs~pkCa#ofx]oes;a$-=t7kBoe"

[[entry]]
title = "花 & 光"
date = 2024-09-18
image_url = "https://2f0f3db.webp.li/2024/09/122326824_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/122326824"
note = """
今天得到消息，因为我来的时间点不太好，所做的工作量不太够，转正名额无法给我，让我考虑以后的出路。说实话我挺感谢这次谈话的，如果一直吊着我，反而会让我没有理由去离开……
我个人的想法也是早点出去，因为这里的工作实在是不太喜欢，没有可以提升的点，并且也受不了这里面“领头羊”一样的陈年代码，一个人写下了错误的代码，其他人就会复制粘贴到其他地方，尽管早期的设计让代码不至于太过凌乱，但内部已经很难维护了。
但我还是有一点小小的失落的。这究竟是一种搪塞，还是我的能力真的不够这份工作呢？
明明感觉到我的能力还是不错的，为什么会有这样的结果？龙游浅水，虎落平阳？
但既然结果已定，那么只有坦然接受，我还是可以安排好我以后的工作的。大鹏一日同风起，扶摇直上九万里！
"""
keywords = ["烟花", "若叶睦"]
blurhash = "U34n-^od02NIxBj[IqWC0LWB~UxZIuay-noe"

[[entry]]
title = "萤与月"
date = 2024-09-19
image_url = "https://2f0f3db.webp.li/2024/09/122480274_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/122480274"
note = """
今天从一块实习的同学那边得知，HR 根本没有留出给实习生的名额，我们两个怕都是要走人了。从这里还是能感觉就业的寒冬啊……本来以为今年的就业形势还不错，没想到还是没有复苏啊！
不过这也是机遇！就像这张图上的萤与月，还是相信会有美好的事情发生。"""
keywords = ["月亮", "光晕"]
blurhash = "UOB}CHyG8{WGDmMz%Jt1Q+RNkUk7%zx[RmRo"

[[entry]]
title = "一起走吧！"
date = 2024-09-20
image_url = "https://2f0f3db.webp.li/2024/09/114055799_p0_master1200.jpg"
origin_url = "https://www.pixiv.net/artworks/114055799"
note = "周五！而且还是没有什么事的周五，组会也和我没有任何关系，可以说是换了个地方自习而已（笑）。今天总结了一下博客性能优化的方面，并且还把 lightinghouse 打到了 0.4s 满分的程度，小小骄傲一下"
keywords = ["花海"]
blurhash = "UGP$h1_3$+%N.TX.t5S4tSN4R.xC?KkDRjW;"

[[entry]]
title = "优雅与冷艳"
date = 2024-09-21
image_url = "https://2f0f3db.webp.li/2024/09/1837058096021262491.jpeg"
origin_url = "https://x.com/miyukiiiiirkgk/status/1837058096021262491"
note = "眼前一亮的画风，可惜画师似乎没有 pixiv 的账号，只能从小蓝鸟上看了"
keywords = ["刀", "优雅", "清冷"]
blurhash = "UGQmCz?v_M_4_M%M?FxZS$ofRQM|_2jFt6E2"

[[entry]]
title = "会议，要迟到了吧！"
date = 2024-09-22
image_url = "https://2f0f3db.webp.li/2024/09/92999806_p0_master1200.jpg"
note = """
不是什么会议……是双选会，深感现在就业之寒冬，简历收了一沓又一沓，能有多少回音呢？
期间有一个公司的 HR（也许是吧），用很浓的说教语气来劝诫我，说了一堆我感觉没有用的东西，不过有一个确实很能让我反思，你打算干前端干一辈子吗？
确实，和后端相比，前端的水确实有点浅，后端面对的是非常高复杂度的场景，高并发，高可用……这些我从来没接触过的名词，而且校内相关的课程设计我也完成的不是很好，但我也不是只有前后端，客户端这样常规的选择，我可不可以再另辟蹊径一些呢？
就像老爹说的，这样干一辈子也是人家的兵，什么时候能有自己的天地。来到浙江这么久，也能见识到浙江人的敢于闯荡的精神，你也有所沾染吧！
除了双选会，还有一个多臂老虎机的视频，是漫士沉思录讲的一个关于选择的问题，只有敢于做选择，并且在事后收敛总结，才更有可能见到更好的解。如果固化自己的思维，也许就会一直困守在一个奇怪的舒适圈内。
所以，休道天凉好个秋，却行水击三千里！"""
keywords = ["矜持"]
blurhash = "UMQ9l=-S_4~q^+DhR*%hcFRl?bxv?b-;IARP"

[[entry]]
title = "归路"
date = 2024-09-23
image_url = "https://2f0f3db.webp.li/2024/09/122532774_p0_master1200.jpg"
note = """
今天我们部门和 AIoT 的新 BOSS 吃饭，饭局上还真是窘迫啊！如果我没有延毕，兴许也不会有今天的样子。
但这条路还是我自己选择的，这份苦还是要吃下去，而且以此为鉴，不要再吃第二次苦，课内的东西还是要抓紧！"""
keywords = ["月亮", "路灯"]
blurhash = "U44Vg=D*Mwoz8}xVtRWD8wxtjsa__LI@M|ax"
