[[entry]]
title = "纸牌城堡"
date = 2024-09-09
image_url = "https://2f0f3db.webp.li/2024/09/89956875_p0_master1200.jpg"
note = "庆祝画廊页面的重构完成！这种感觉确实很像是搭纸牌城堡，莫名有一种契合（笑）"
keywords = ["城堡", "公主", "优雅"]
blurhash = "UxKwCFIURPs:~qaKRjV@%gayV@WBkWs:jFae"

[[entry]]
title = "追寻"
date = 2024-09-10
image_url = "https://2f0f3db.webp.li/2024/09/122295149_p0_master1200.jpg"
note = "今天是生日，也是准备面试的第二天，忙的连轴转，也算是一起在追寻！总是在寻找一些美好的东西"
keywords = ["银发"]
blurhash = "UADJJ5^-009F=SRh4?IV00E1^+bX0@oh~9xt"

[[entry]]
title = "流星"
date = 2024-09-11
image_url = "https://2f0f3db.webp.li/2024/09/122228116_p0_master1200.jpg"
note = "流星的意思是出货吗（笑），请假一天，好好准备吧！"
keywords = ["流星", "许愿"]
blurhash = "U9C~Y~x|}$Ae009X0e$,[%^Ekr%N%OAL-XEM"
